# Generated by Django 5.0.4 on 2024-04-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_link_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='link_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag')),
            ],
        ),
    ]
